import { NextRequest, NextResponse } from "next/server";
import connectDB from "@/lib/mongodb";
import { Event } from "@/app/database";
import { rateLimit, getClientIp } from "@/lib/rateLimiter";
import {
  ValidationError,
  validateCloudinaryConfig,
  validateEventFormData,
  uploadEventImageToCloudinary,
} from "@/lib/event-form-validation";

// ─── Rate limiting config ────────────────────────────────────────────────────
const RATE_LIMIT_WINDOW_MS = 60_000; // 1 minute
const RATE_LIMIT_MAX_POST = 10; // 10 POST requests per minute
const RATE_LIMIT_MAX_GET = 30; // 30 GET requests per minute

// ─── POST /api/events ────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  // Rate limit check
  const ip = getClientIp(req);
  const rateCheck = rateLimit(`post:${ip}`, RATE_LIMIT_MAX_POST, RATE_LIMIT_WINDOW_MS);
  if (!rateCheck.allowed) {
    return NextResponse.json(
      {
        message: "Too many requests. Please try again later.",
        retryAfterSeconds: rateCheck.resetInSeconds,
      },
      {
        status: 429,
        headers: {
          "Retry-After": String(rateCheck.resetInSeconds),
          "X-RateLimit-Remaining": "0",
        },
      },
    );
  }

  try {
    // Validate Cloudinary config early
    validateCloudinaryConfig();

    await connectDB();

    const formData = await req.formData();

    // Validate all form fields
    const fields = validateEventFormData(formData);

    // Validate and process image
    const file = formData.get("image") as File | null;
    if (!file) {
      return NextResponse.json(
        { message: "Image file is required" },
        { status: 400 },
      );
    }

    // Upload image to Cloudinary
    const secureUrl = await uploadEventImageToCloudinary(file);

    // Create event in database
    // Slug is auto-generated by the Event model's pre-save hook
    const createdEvent = await Event.create({
      title: fields.title,
      description: fields.description,
      overview: fields.overview,
      image: secureUrl,
      venue: fields.venue,
      location: fields.location,
      date: fields.date,
      time: fields.time,
      mode: fields.mode,
      audience: fields.audience,
      organizer: fields.organizer,
      tags: fields.tags,
      agenda: fields.agenda,
    });

    return NextResponse.json(
      { message: "Event created successfully", event: createdEvent },
      { status: 201 },
    );
  } catch (e) {
    console.error("Event creation failed:", e);

    // Return 400 for known validation errors
    if (e instanceof ValidationError) {
      return NextResponse.json({ message: e.message }, { status: 400 });
    }

    if (e instanceof Error && e.message.startsWith("Cloudinary")) {
      return NextResponse.json({ message: e.message }, { status: 400 });
    }

    return NextResponse.json(
      {
        message: "Event creation failed",
        error: e instanceof Error ? e.message : "Unknown",
      },
      { status: 500 },
    );
  }
}

// ─── GET /api/events ─────────────────────────────────────────────────────────

export async function GET(req: NextRequest) {
  // Rate limit check
  const ip = getClientIp(req);
  const rateCheck = rateLimit(`get:${ip}`, RATE_LIMIT_MAX_GET, RATE_LIMIT_WINDOW_MS);
  if (!rateCheck.allowed) {
    return NextResponse.json(
      {
        message: "Too many requests. Please try again later.",
        retryAfterSeconds: rateCheck.resetInSeconds,
      },
      {
        status: 429,
        headers: {
          "Retry-After": String(rateCheck.resetInSeconds),
          "X-RateLimit-Remaining": "0",
        },
      },
    );
  }

  try {
    await connectDB();
    const events = await Event.find().sort({ createdAt: -1 });

    return NextResponse.json(
      { message: "Events fetched successfully", events },
      { status: 200 },
    );
  } catch (e) {
    console.error("Event fetching failed:", e);
    return NextResponse.json(
      {
        message: "Event fetching failed",
        error: e instanceof Error ? e.message : "Unknown",
      },
      { status: 500 },
    );
  }
}
